Allow headers include with <>
Vertexwahn/rules_qt6 pull request #16
Opened 2023-07-07 20:46 UTC by dieortin

Apply the patch suggested by ankit-agarwal1999, which allows linux builds to use both official ways to include Qt headers.

https://github.com/Vertexwahn/rules_qt6/issues/12#issuecomment-1423059773

2023-07-07 23:00 UTC, Vertexwahn commented
@dieortin Can you do the same change to the other files, e.g. [qt_mac_aarch64.BUILD](https://github.com/Vertexwahn/rules_qt6/blob/main/qt_mac_aarch64.BUILD), [qt_mac_x86_64.BUILD](https://github.com/Vertexwahn/rules_qt6/blob/main/qt_mac_x86_64.BUILD) and [qt_windows_x86_64.BUILD](https://github.com/Vertexwahn/rules_qt6/blob/main/qt_windows_x86_64.BUILD). 

To make sure that this change work (now and in the future) please adapt at least one example in the test folder https://github.com/Vertexwahn/rules_qt6/blob/66720061b91a2d5516faa63ad91f610cccd48905/tests/hello_world/hello_world.cpp#L1

2023-07-07 23:41 UTC, Vertexwahn requested changes
@dieortin Can you do the same change to the other files, e.g. [qt_mac_aarch64.BUILD](https://github.com/Vertexwahn/rules_qt6/blob/main/qt_mac_aarch64.BUILD), [qt_mac_x86_64.BUILD](https://github.com/Vertexwahn/rules_qt6/blob/main/qt_mac_x86_64.BUILD) and [qt_windows_x86_64.BUILD](https://github.com/Vertexwahn/rules_qt6/blob/main/qt_windows_x86_64.BUILD). To make sure that this change work (now and in the future) please adapt at least one example in the test folder https://github.com/Vertexwahn/rules_qt6/blob/66720061b91a2d5516faa63ad91f610cccd48905/tests/hello_world/hello_world.cpp#L1

BTW: VS2022 is currently broken because of an Bazel error -> https://github.com/bazelbuild/bazel/issues/18592 - you can ignore the VS2022 job for now - but VS2019 should work...

2023-07-08 00:37 UTC, dieortin commented
The changes you requested are done and locally tested on Linux x86_64

2023-07-08 08:20 UTC, Vertexwahn approved these changes
Thanks for your contribution!

2023-07-08 08:21 UTC, merged